version: '3.9'
services:
  # アプリケーションのコンテナ
  app:
    container_name: app_container
    build: ./docker/app
    ports:
      - 3000:3000
    volumes:
      - ./client:/app/client:cached
      - ./server:/app/server:cached
    working_dir: /app
    command: sh -c "cd client && yarn start"
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
  # DBのコンテナ
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306" #ホストの33060番ポートとコンテナの3306番ポートをマッピング
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}